### ISSUE TITLE
Mostrar texto documento debajo de información general?

### ISSUE THREAD

**Issue by pablojan** [Grasia/collaborative-writting-base#1]
Por qué mostrar el documento aqui?

https://github.com/Grasia/collaborative-writting-base/blob/dbe8925e5cf0f3e6be2bba5d7bd2da1803a1b2ca/src/app/documento
![imagen](https://user-images.githubusercontent.com/4454927/37769753-52a04164-2dd2-11e8-8d78-2199efa7e526.png)

**Comment by Jorgefmc** [comment]
Fail logístico que se paso eliminar antes del commit, arreglado ya.
